---
# Source: copy-fail-blocker/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: copy-fail-blocker
  namespace: kube-system
  labels:
    app.kubernetes.io/name: copy-fail-blocker
    app.kubernetes.io/instance: copy-fail-blocker
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: copy-fail-blocker-0.2.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: copy-fail-blocker
      app.kubernetes.io/instance: copy-fail-blocker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: copy-fail-blocker
        app.kubernetes.io/instance: copy-fail-blocker
    spec:
      hostPID: false
      hostNetwork: false
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
      containers:
        - name: blocker
          image: "docker.io/oxeva/copyfail:1.0@sha256:857eabd647ceebc659ea2af8b4be91f9559c257a8144efc029182035afdc74f4"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            runAsUser: 0
          resources:
            limits:
              memory: 64Mi
            requests:
              cpu: 5m
              memory: 16Mi
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: bpffs
              mountPath: /sys/fs/bpf
              mountPropagation: HostToContainer
      volumes:
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: bpffs
          hostPath:
            path: /sys/fs/bpf
            type: Directory
