apiVersion: v2
name: copy-fail-blocker
description: BPF-LSM hook blocking AF_ALG, AF_RXRPC and NETLINK_XFRM (CVE-2026-31431 / dirtyfrag mitigation)
type: application
version: 0.2.1
appVersion: "0.2.0"
home: https://github.com/odoucet/copyfail-dirtyfrag-blocker
sources:
  - https://github.com/odoucet/copyfail-dirtyfrag-blocker
keywords:
  - bpf
  - lsm
  - security
  - cve-2026-31431
  - dirtyfrag
  - af_alg
  - af_rxrpc
  - netlink_xfrm
