image:
  repository: docker.io/oxeva/copyfail
  tag: 1.0@sha256:857eabd647ceebc659ea2af8b4be91f9559c257a8144efc029182035afdc74f4
  pullPolicy: IfNotPresent
imagePullSecrets: []
priorityClassName: system-node-critical
resources:
  requests:
    cpu: 5m
    memory: 16Mi
  limits:
    memory: 64Mi
tolerations:
  - operator: Exists
nodeSelector: {}
affinity: {}
